<?xml version="1.0" encoding="utf-8"?>
<S:log-report xmlns:S="svn:" xmlns:D="DAV:">
<S:log-item>
<D:version-name>1129799</D:version-name>
<D:comment>DERBY-5243 assert failure in test testRAFReadWriteMultipleThreads: interrupted flag cleared

Backported cleanly from trunk as:

svn merge -c 1129797 https://svn.apache.org/repos/asf/db/derby/code/trunk

Patch DERBY-5243-1: It moves the setting of the interrupted flag to
just before CONN_INTERRUPT exception is thrown as an SQLException back
to the user application, i.e. as late as possible. Previously, we set
the interrupted flag when we first threw the internal
StandardException. The new placement means that we are done with IO to
derby.log which may be behind the problem we are seeing on older
VMs. I ran the new version 100 times on Linux/JDK 5 without seeing the
error, which previously appeared in ca 20% of the runs.


</D:comment>
<D:creator-displayname>dag</D:creator-displayname>
<S:date>2011-05-31T16:56:09.417504Z</S:date>
</S:log-item>
</S:log-report>
