{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12393472","self":"https://issues.apache.org/jira/rest/api/latest/issue/12393472","key":"LUCENE-1262","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310110","id":"12310110","key":"LUCENE","name":"Lucene - Core","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310110&avatarId=10061","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310110&avatarId=10061","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310110&avatarId=10061","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310110&avatarId=10061"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10150","id":"10150","description":"Lucene-related projects","name":"Lucene"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313057","id":"12313057","description":" Bug Fixes for the 2.3.1 release","name":"2.3.2","archived":false,"released":true,"releaseDate":"2008-05-06"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12312681","id":"12312681","description":"","name":"2.4","archived":false,"released":true,"releaseDate":"2008-10-08"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12310220":"2008-04-09 09:51:19.37","customfield_12312323":null,"customfield_12310420":"12486","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_428657209_*|*_6_*:*_1_*:*_0_*|*_5_*:*_1_*:*_2146822725","customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2008-04-13T23:27:36.209+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/LUCENE-1262/watchers","watchCount":1,"isWatching":false},"created":"2008-04-09T00:23:19.272+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"2.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12312330":null,"customfield_12311120":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312975","id":"12312975","description":"Bug Fixes for the 2.3.0 release","name":"2.3.1","archived":false,"released":true,"releaseDate":"2008-02-22"}],"issuelinks":[],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2008-05-08T19:47:58.933+0000","customfield_12312335":null,"customfield_12312336":null,"customfield_12311720":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12310232","id":"12310232","name":"core/index","description":"issues with indexing code"}],"timeoriginalestimate":null,"description":"There is a situation where there is an IOException reading from Hits, and then the next time you get a NullPointerException instead of an IOException.\n\nExample stack traces:\n\njava.io.IOException: The specified network name is no longer available\n\tat java.io.RandomAccessFile.readBytes(Native Method)\n\tat java.io.RandomAccessFile.read(RandomAccessFile.java:322)\n\tat org.apache.lucene.store.FSIndexInput.readInternal(FSDirectory.java:536)\n\tat org.apache.lucene.store.BufferedIndexInput.readBytes(BufferedIndexInput.java:74)\n\tat org.apache.lucene.index.CompoundFileReader$CSIndexInput.readInternal(CompoundFileReader.java:220)\n\tat org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:93)\n\tat org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:34)\n\tat org.apache.lucene.store.IndexInput.readVInt(IndexInput.java:57)\n\tat org.apache.lucene.index.FieldsReader.doc(FieldsReader.java:88)\n\tat org.apache.lucene.index.SegmentReader.document(SegmentReader.java:344)\n\tat org.apache.lucene.index.IndexReader.document(IndexReader.java:368)\n\tat org.apache.lucene.search.IndexSearcher.doc(IndexSearcher.java:84)\n\tat org.apache.lucene.search.Hits.doc(Hits.java:104)\n\nThat error is fine.  The problem is the next call to doc generates:\n\njava.lang.NullPointerException\n\tat org.apache.lucene.index.FieldsReader.getIndexType(FieldsReader.java:280)\n\tat org.apache.lucene.index.FieldsReader.addField(FieldsReader.java:216)\n\tat org.apache.lucene.index.FieldsReader.doc(FieldsReader.java:101)\n\tat org.apache.lucene.index.SegmentReader.document(SegmentReader.java:344)\n\tat org.apache.lucene.index.IndexReader.document(IndexReader.java:368)\n\tat org.apache.lucene.search.IndexSearcher.doc(IndexSearcher.java:84)\n\tat org.apache.lucene.search.Hits.doc(Hits.java:104)\n\nPresumably FieldsReader is caching partially-initialised data somewhere.  I would normally expect the exact same IOException to be thrown for subsequent calls to the method.\n","customfield_10010":null,"timetracking":{},"customfield_12310120":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10121","value":"New","id":"10121"}],"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"26784","summary":"IndexOutOfBoundsException from FieldsReader after problem reading the index","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":8,"total":8,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587117","id":"12587117","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Those stack traces look like 2.1 not 2.3.1.  Is that right?\r\n\r\nCan you post the index that you are using and the code that results in the 2nd exception?  I can't get the 2nd exception to happen in a test case...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2008-04-09T09:51:19.370+0000","updated":"2008-04-09T09:51:19.370+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587418","id":"12587418","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"body":"Whoops.  I don't think it's 2.1 but it must be 2.2.\r\n\r\nI'll try and reproduce this standalone but first I need a way to have readInternal throw an exception.  I presume you were using some kind of custom store implementation to do that, I'll see if I can make it happen.under 2.2 and then try the same thing under 2.3.1 to confirm whether it still breaks.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"created":"2008-04-09T23:08:23.947+0000","updated":"2008-04-09T23:08:23.947+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587433","id":"12587433","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"body":"Okay I'll eat my words now, it is indeed 2.1 as the version doesn't have openInput(String,int) in it.\r\n\r\nAnyway an update: I've managed to reproduce it on any text index by simulating random network outage.  I'm keeping a flag which I set to true.  The trick is that the wrapping IndexInput implementation *randomly* throws IOException if the flag is true -- if it always throws IOException the problem doesn't occur.  If it randomly throws it then it occurs occasionally, and it always seems to be for larger queries (I'm using MatchAllDocsQuery now.)\r\n\r\nI'll see if I can tweak the code to make it more likely to happen and then start working up to each version of Lucene to see if it stops happening somewhere.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"created":"2008-04-10T00:01:02.778+0000","updated":"2008-04-10T00:01:02.778+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587439","id":"12587439","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"body":"I managed to reproduce the problem as-is under version 2.2.\r\n\r\nFor 2.3 the problem has changed -- instead of a NullPointerException it is now an IndexOutOfBoundsException:\r\n\r\nException in thread \"main\" java.lang.IndexOutOfBoundsException: Index: 52, Size: 34\r\n        at java.util.ArrayList.RangeCheck(ArrayList.java:547)\r\n        at java.util.ArrayList.get(ArrayList.java:322)\r\n        at org.apache.lucene.index.FieldInfos.fieldInfo(FieldInfos.java:260)\r\n        at org.apache.lucene.index.FieldsReader.doc(FieldsReader.java:154)\r\n        at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:659)\r\n        at org.apache.lucene.index.IndexReader.document(IndexReader.java:525)\r\n        at org.apache.lucene.search.IndexSearcher.doc(IndexSearcher.java:92)\r\n        at org.apache.lucene.search.Hits.doc(Hits.java:167)\r\n        at Test.main(Test.java:24)\r\n\r\nWill attach my test program in a moment.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"created":"2008-04-10T00:29:18.379+0000","updated":"2008-04-10T00:29:18.379+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587440","id":"12587440","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"body":"Attaching a test program to reproduce the problem under 2.3.1.\r\n\r\nIt occurs approximately 1 in every 4 executions for any reasonably large text index (really small ones don't seem to do it so I couldn't attach a text index with it.)  The number of fields may be related, looking at the IndexOutOfBoundsException numbers it seems that the indexes we have happen to have a large number of fields.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=trejkaz","name":"trejkaz","emailAddress":"trejkaz at trypticon dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Trejkaz","active":true},"created":"2008-04-10T00:31:25.888+0000","updated":"2008-04-10T00:31:25.888+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587896","id":"12587896","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"OK indeed I can get the failure to happen, using your Test running against a partial Wikipedia index I have.  I'll pursue!  Thanks Trejkaz.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2008-04-11T09:21:56.902+0000","updated":"2008-04-11T09:21:56.902+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12587911","id":"12587911","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Attached patch.  All tests pass.  I plan to commit in a day or so, to\r\nboth trunk (2.4) and 2.3.X branch (2.3.2).\r\n\r\nI got the failure to happen with a standalone test case, added to\r\nTestFieldsReader.\r\n\r\nI found & fixed the issue.  It's in BufferedIndexReader's refill()\r\nmethod.  The problem is that method changes bufferLength even if an\r\nexception is hit.  This leaves incorrect bytes in the buffer such that\r\na subsequent readByte will return the incorrect bytes.\r\n\r\nThe fix is simple: use a local \"int newLength\" and only assign that to\r\nvalue to bufferLength if the readInternal() call succeeds.  The test\r\nfails without the fix and passes with it.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2008-04-11T10:20:54.337+0000","updated":"2008-04-11T10:20:54.337+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12393472/comment/12588453","id":"12588453","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"I just committed this.  Thanks Trejkaz!","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2008-04-13T23:27:36.163+0000","updated":"2008-04-13T23:27:36.163+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/LUCENE-1262/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i04y2f:"}}