{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12510477","self":"https://issues.apache.org/jira/rest/api/latest/issue/12510477","key":"DERBY-5279","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313143","id":"12313143","description":"Head of 10.3 branch","name":"10.3.3.1","archived":false,"released":false}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2011-06-16 08:13:50.971","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"24754","customfield_12310222":"1_*:*_1_*:*_38616733987_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2012-09-04T16:35:26.297+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5279/watchers","watchCount":1,"isWatching":false},"created":"2011-06-15T17:43:12.337+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313143","id":"12313143","description":"Head of 10.3 branch","name":"10.3.3.1","archived":false,"released":false}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2013-06-19T17:19:45.310+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"The following has failed in a number of tinderbox runs, but not always.  For example it has failed as reported in:\r\nhttp://dbtg.foundry.sun.com/derby/test/tinderbox_10.3_16/jvm1.6/testing/testlog/SunOS-5.10_i86pc-i386/1055890-org.apache.derbyTesting.functionTests.suites.All_diff.txt\r\nBut not fail in the subsequent run:\r\nhttp://dbtg.foundry.sun.com/derby/test/tinderbox_10.3_16/jvm1.6/testing/testlog/SunOS-5.10_i86pc-i386/1056412-derbyall_diff.txt\r\nBut then fails again in the most recent run:\r\nhttp://dbtg.foundry.sun.com/derby/test/tinderbox_10.3_16/jvm1.6/testing/testlog/SunOS-5.10_i86pc-i386/1135825-org.apache.derbyTesting.functionTests.suites.All_diff.txt\r\nThere was 1 error:\r\n1) test5DeleteBeforeTriggerNoReferencingClause(org.apache.derbyTesting.functionTests.tests.memory.TriggerTests)java.sql.SQLException: Table/View 'TABLE1' already exists in Schema 'APP'.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:95)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:202)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:391)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:1593)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1294)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:528)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.basicSetup(TriggerTests.java:267)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.test5DeleteBeforeTriggerNoReferencingClause(TriggerTests.java:1221)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:99)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLException: Table/View 'TABLE1' already exists in Schema 'APP'.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\t... 41 more\r\nCaused by: ERROR X0Y32: Table/View 'TABLE1' already exists in Schema 'APP'.\r\n\tat org.apache.derby.iapi.error.StandardException.newException(StandardException.java:371)\r\n\tat org.apache.derby.impl.sql.catalog.DataDictionaryImpl.duplicateDescriptorException(DataDictionaryImpl.java:1683)\r\n\tat org.apache.derby.impl.sql.catalog.DataDictionaryImpl.addDescriptor(DataDictionaryImpl.java:1674)\r\n\tat org.apache.derby.impl.sql.catalog.DataDictionaryImpl.addDescriptor(DataDictionaryImpl.java:1653)\r\n\tat org.apache.derby.impl.sql.execute.CreateTableConstantAction.executeConstantAction(CreateTableConstantAction.java:238)\r\n\tat org.apache.derby.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:64)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\t... 35 more\r\n\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10369","value":"Regression Test Failure","id":"10369"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"35474","summary":"test5DeleteBeforeTriggerNoReferencingClause fails in nightly testing","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"failing in posted 10.3 tinderbox on sun jvm:\r\norg.apache.derbyTesting.functionTests.suites.All diff -------------------------------------------------------------\r\n------------------ Java Information ------------------\r\nJava Version:    1.6.0_18\r\nJava Vendor:     Sun Microsystems Inc.\r\nJava home:       /usr/local/java/jdk1.6.0_18/jre\r\nJava classpath:  /home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derby.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyclient.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbytools.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbynet.jar:/home/os136789/Apache/TinderBox-10.3/db2jcc/lib/db2jcc.jar:/home/os136789/Apache/TinderBox-10.3/db2jcc/lib/db2jcc_license_c.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyTesting.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyrun.jar:/home/os136789/Apache/TinderBox-10.3/10.3/tools/java/jakarta-oro-2.0.8.jar:/home/os136789/Apache/TinderBox-10.3/10.3/tools/java/junit.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_de_DE.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_es.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_fr.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_it.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_ja_JP.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_ko_KR.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_pt_BR.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_zh_CN.jar:/home/os136789/Apache/TinderBox-10.3/10.3/jars/insane/derbyLocale_zh_TW.jar:/usr/local/share/java/xalan/serializer.jar:/usr/local/share/java/xalan/xalan.jar:/usr/local/share/java/xalan/xercesImpl.jar:/usr/local/share/java/xalan/xml-apis.jar:/usr/local/share/java/xalan/xsltc.jar\r\nOS name:         SunOS\r\nOS architecture: x86\r\nOS version:      5.10\r\nJava user name:  os136789\r\nJava user home:  /home/os136789\r\nJava user dir:   /export/home/tmp/os136789/testingDerbyTinderBox-10.3/SunOS-5.10_i86pc-i386/org.apache.derbyTesting.functionTests.suites.All\r\njava.specification.name: Java Platform API Specification\r\njava.specification.version: 1.6\r\n--------- Derby Information --------\r\nJRE - JDBC: Java SE 6 - JDBC 4.0\r\n[/export/home/tmp/os136789/10.3/jars/insane/derby.jar] 10.3.3.1 - (1055890)\r\n[/export/home/tmp/os136789/10.3/jars/insane/derbytools.jar] 10.3.3.1 - (1055890)\r\n[/export/home/tmp/os136789/10.3/jars/insane/derbynet.jar] 10.3.3.1 - (1055890)\r\n[/export/home/tmp/os136789/10.3/jars/insane/derbyclient.jar] 10.3.3.1 - (1055890)\r\n[/home/os136789/Apache/TinderBox_Derby/db2jcc/lib/db2jcc.jar] 2.4 - (17)\r\n[/home/os136789/Apache/TinderBox_Derby/db2jcc/lib/db2jcc_license_c.jar] 2.4 - (17)\r\n------------------------------------------------------\r\n----------------- Locale Information -----------------\r\nCurrent Locale :  [English/United States [en_US]]\r\nFound support for locale: [cs]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [de_DE]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [es]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [fr]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [hu]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [it]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [ja_JP]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [ko_KR]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [pl]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [pt_BR]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [ru]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [zh_CN]\r\n\t version: 10.3.3.1 - (1055890)\r\nFound support for locale: [zh_TW]\r\n\t version: 10.3.3.1 - (1055890)\r\n------------------------------------------------------\r\n","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":6,"total":6,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13049916","id":"13049916","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"The error has the feel of some bad cleanup in the test.  Has there been some test  fix that may not have been backported to 10.3?\r\n\r\nI checked the last 10 or so runs against 4 different ibm jvm's on 10.3 and don't see the problem.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2011-06-15T17:45:40.905+0000","updated":"2011-06-15T17:45:40.905+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13050278","id":"13050278","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"This sounds similar to the problems we saw in this test after DERBY-4874. TriggerTests.basicSetup() ignores all exceptions thrown by DROP TABLE statements on the assumption that they indicate that the table already exists. In DERBY-4874 one of the statements failed because of a lock timeout (lock conflict with the post-commit thread), so the table actually existed, and the CREATE TABLE statement failed.\r\n\r\nTo investigate this, you may want to make basicSetup() on the 10.3 branch report unexpected exceptions from the DROP TABLE statements (on trunk we use a helper method in BaseJDBCTestCase for this), and if the problem is a lock timeout, check what the lock timeout is when the test is running (tests running earlier may have lowered the timeout without restoring it).","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2011-06-16T08:13:50.971+0000","updated":"2011-06-16T08:13:50.971+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13050649","id":"13050649","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Knut, what a coincidence. I am just getting ready to checkin the changes where while dropping the table, we only ignore table not found error and pass the rest of the errors to the test so the failure exception will show us what kind of error drop table received. For some reason, we backported this change all the way to 10.4 but not to 10.3","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2011-06-16T18:55:37.416+0000","updated":"2011-06-16T18:55:37.416+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13050829","id":"13050829","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"I made another checkin which will catch lock timeout exception and print the current derby lock time out at the time the exception was received. This change went in as 1136717","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2011-06-17T00:30:39.618+0000","updated":"2011-06-17T00:30:39.618+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13052636","id":"13052636","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"The test failed again after putting in the new diagnostics.  I see it is fails with a lock timeout.\r\n\r\nhttp://dbtg.foundry.sun.com/derby/test/tinderbox_10.3_16/jvm1.6/testing/testlog/SunOS-5.10_i86pc-i386/1136736-org.apache.derbyTesting.functionTests.suites.All_diff.txt\r\n\r\nThere were 2 failures:\r\n1) test5DeleteBeforeTriggerNoReferencingClause(org.apache.derbyTesting.functionTests.tests.memory.TriggerTests)junit.framework.ComparisonFailure: Unexpected SQL state. expected:<4[2Y55]> but was:<4[0XL1]>\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:651)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:700)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:832)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:813)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.basicSetup(TriggerTests.java:245)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.test5DeleteBeforeTriggerNoReferencingClause(TriggerTests.java:1231)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:99)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:88)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:202)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:391)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:1593)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1294)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:830)\r\n\t... 34 more\r\nCaused by: java.sql.SQLException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\t... 43 more\r\nCaused by: ERROR 40XL1: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.iapi.error.StandardException.newException(StandardException.java:280)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(ConcurrentLockSet.java:602)\r\n\tat org.apache.derby.impl.services.locks.AbstractPool.lockObject(AbstractPool.java:117)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentPool.lockObject(ConcurrentPool.java:28)\r\n\tat org.apache.derby.impl.store.raw.xact.ContainerLocking3.lockContainer(ContainerLocking3.java:64)\r\n\tat org.apache.derby.impl.store.raw.data.BaseContainerHandle.useContainer(BaseContainerHandle.java:809)\r\n\tat org.apache.derby.impl.store.raw.data.BaseDataFileFactory.openContainer(BaseDataFileFactory.java:632)\r\n\tat org.apache.derby.impl.store.raw.data.BaseDataFileFactory.openContainer(BaseDataFileFactory.java:572)\r\n\tat org.apache.derby.impl.store.raw.xact.Xact.openContainer(Xact.java:1300)\r\n\tat org.apache.derby.impl.store.access.conglomerate.OpenConglomerate.init(OpenConglomerate.java:863)\r\n\tat org.apache.derby.impl.store.access.heap.Heap.open(Heap.java:686)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.openConglomerate(RAMTransaction.java:486)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.openConglomerate(RAMTransaction.java:1327)\r\n\tat org.apache.derby.impl.sql.execute.DDLConstantAction.lockTableForDDL(DDLConstantAction.java:135)\r\n\tat org.apache.derby.impl.sql.execute.DropTableConstantAction.executeConstantAction(DropTableConstantAction.java:164)\r\n\tat org.apache.derby.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:61)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\t... 37 more\r\n2) test5UpdateAfterTriggerNoReferencingClause(org.apache.derbyTesting.functionTests.tests.memory.TriggerTests)junit.framework.ComparisonFailure: Unexpected SQL state. expected:<4[2Y55]> but was:<4[0XL1]>\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:651)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:700)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:832)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:813)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.basicSetup(TriggerTests.java:245)\r\n\tat org.apache.derbyTesting.functionTests.tests.memory.TriggerTests.test5UpdateAfterTriggerNoReferencingClause(TriggerTests.java:1246)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:99)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:88)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:202)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:391)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:1593)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1294)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.dropTable(BaseJDBCTestCase.java:830)\r\n\t... 34 more\r\nCaused by: java.sql.SQLException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\t... 43 more\r\nCaused by: ERROR 40XL1: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.iapi.error.StandardException.newException(StandardException.java:280)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(ConcurrentLockSet.java:602)\r\n\tat org.apache.derby.impl.services.locks.AbstractPool.lockObject(AbstractPool.java:117)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentPool.lockObject(ConcurrentPool.java:28)\r\n\tat org.apache.derby.impl.store.raw.xact.ContainerLocking3.lockContainer(ContainerLocking3.java:64)\r\n\tat org.apache.derby.impl.store.raw.data.BaseContainerHandle.useContainer(BaseContainerHandle.java:809)\r\n\tat org.apache.derby.impl.store.raw.data.BaseDataFileFactory.openContainer(BaseDataFileFactory.java:632)\r\n\tat org.apache.derby.impl.store.raw.data.BaseDataFileFactory.openContainer(BaseDataFileFactory.java:572)\r\n\tat org.apache.derby.impl.store.raw.xact.Xact.openContainer(Xact.java:1300)\r\n\tat org.apache.derby.impl.store.access.conglomerate.OpenConglomerate.init(OpenConglomerate.java:863)\r\n\tat org.apache.derby.impl.store.access.heap.Heap.open(Heap.java:686)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.openConglomerate(RAMTransaction.java:486)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.openConglomerate(RAMTransaction.java:1327)\r\n\tat org.apache.derby.impl.sql.execute.DDLConstantAction.lockTableForDDL(DDLConstantAction.java:135)\r\n\tat org.apache.derby.impl.sql.execute.DropTableConstantAction.executeConstantAction(DropTableConstantAction.java:164)\r\n\tat org.apache.derby.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:61)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\t... 37 more\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2011-06-21T16:09:55.318+0000","updated":"2011-06-21T16:09:55.318+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510477/comment/13447801","id":"13447801","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"The test has not failed in over a year. I will close it for now. If it reproduces, we can reopen the issue.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2012-09-04T16:35:26.307+0000","updated":"2012-09-04T16:35:26.307+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5279/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06fof:"}}