{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12475017","self":"https://issues.apache.org/jira/rest/api/latest/issue/12475017","key":"LUCENE-2666","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310110","id":"12310110","key":"LUCENE","name":"Lucene - Core","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310110&avatarId=10061","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310110&avatarId=10061","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310110&avatarId=10061","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310110&avatarId=10061"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10150","id":"10150","description":"Lucene-related projects","name":"Lucene"}},"fixVersions":[],"aggregatetimespent":null,"resolution":null,"customfield_12312322":null,"customfield_12310220":"2010-09-24 10:23:22.855","customfield_12312323":null,"customfield_12310420":"11175","customfield_12312320":null,"customfield_12310222":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":null,"workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/LUCENE-2666/watchers","watchCount":1,"isWatching":false},"created":"2010-09-24T09:06:48.668+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12312330":null,"customfield_12311120":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12314798","id":"12314798","description":"Bugfixes for 3.0.1","name":"3.0.2","archived":false,"released":true,"releaseDate":"2010-06-18"}],"issuelinks":[],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2011-02-07T19:46:51.249+0000","customfield_12312335":null,"customfield_12312336":null,"customfield_12311720":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/1","description":"The issue is open and ready for the assignee to start work on it.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/open.png","name":"Open","id":"1","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"New"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12310232","id":"12310232","name":"core/index","description":"issues with indexing code"}],"timeoriginalestimate":null,"description":"A user got this very strange exception, and I managed to get the index that it happens on. Basically, iterating over the TermDocs causes an AAOIB exception. I easily reproduced it using the FieldCache which does exactly that (the field in question is indexed as numeric). Here is the exception:\r\n\r\nException in thread \"main\" java.lang.ArrayIndexOutOfBoundsException: 114\r\n\tat org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n\tat org.apache.lucene.index.SegmentTermDocs.next(SegmentTermDocs.java:127)\r\n\tat org.apache.lucene.search.FieldCacheImpl$LongCache.createValue(FieldCacheImpl.java:501)\r\n\tat org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:183)\r\n\tat org.apache.lucene.search.FieldCacheImpl.getLongs(FieldCacheImpl.java:470)\r\n\tat TestMe.main(TestMe.java:56)\r\n\r\nIt happens on the following segment: _26t docCount: 914 delCount: 1 delFileName: _26t_1.del\r\n\r\nAnd as you can see, it smells like a corner case (it fails for document number 912, the AIOOB happens from the deleted docs). The code to recreate it is simple:\r\n\r\n        FSDirectory dir = FSDirectory.open(new File(\"index\"));\r\n        IndexReader reader = IndexReader.open(dir, true);\r\n\r\n        IndexReader[] subReaders = reader.getSequentialSubReaders();\r\n        for (IndexReader subReader : subReaders) {\r\n            Field field = subReader.getClass().getSuperclass().getDeclaredField(\"si\");\r\n            field.setAccessible(true);\r\n            SegmentInfo si = (SegmentInfo) field.get(subReader);\r\n            System.out.println(\"--> \" + si);\r\n            if (si.getDocStoreSegment().contains(\"_26t\")) {\r\n                // this is the probleatic one...\r\n                System.out.println(\"problematic one...\");\r\n                FieldCache.DEFAULT.getLongs(subReader, \"__documentdate\", FieldCache.NUMERIC_UTILS_LONG_PARSER);\r\n            }\r\n        }\r\n\r\nHere is the result of a check index on that segment:\r\n\r\n  8 of 10: name=_26t docCount=914\r\n    compound=true\r\n    hasProx=true\r\n    numFiles=2\r\n    size (MB)=1.641\r\n    diagnostics = {optimize=false, mergeFactor=10, os.version=2.6.18-194.11.1.el5.centos.plus, os=Linux, mergeDocStores=true, lucene.version=3.0.2 953716 - 2010-06-11 17:13:53, source=merge, os.arch=amd64, java.version=1.6.0, java.vendor=Sun Microsystems Inc.}\r\n    has deletions [delFileName=_26t_1.del]\r\n    test: open reader.........OK [1 deleted docs]\r\n    test: fields..............OK [32 fields]\r\n    test: field norms.........OK [32 fields]\r\n    test: terms, freq, prox...ERROR [114]\r\njava.lang.ArrayIndexOutOfBoundsException: 114\r\n\tat org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n\tat org.apache.lucene.index.SegmentTermDocs.next(SegmentTermDocs.java:127)\r\n\tat org.apache.lucene.index.SegmentTermPositions.next(SegmentTermPositions.java:102)\r\n\tat org.apache.lucene.index.CheckIndex.testTermIndex(CheckIndex.java:616)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:509)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:299)\r\n\tat TestMe.main(TestMe.java:47)\r\n    test: stored fields.......ERROR [114]\r\njava.lang.ArrayIndexOutOfBoundsException: 114\r\n\tat org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n\tat org.apache.lucene.index.ReadOnlySegmentReader.isDeleted(ReadOnlySegmentReader.java:34)\r\n\tat org.apache.lucene.index.CheckIndex.testStoredFields(CheckIndex.java:684)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:512)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:299)\r\n\tat TestMe.main(TestMe.java:47)\r\n    test: term vectors........ERROR [114]\r\njava.lang.ArrayIndexOutOfBoundsException: 114\r\n\tat org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n\tat org.apache.lucene.index.ReadOnlySegmentReader.isDeleted(ReadOnlySegmentReader.java:34)\r\n\tat org.apache.lucene.index.CheckIndex.testTermVectors(CheckIndex.java:721)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:515)\r\n\tat org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:299)\r\n\tat TestMe.main(TestMe.java:47)\r\n\r\n\r\n\r\nThe creation of the index does not do something fancy (all defaults), though there is usage of the near real time aspect (IndexWriter#getReader) which does complicate deleted docs handling. Seems like the deleted docs got written without matching the number of docs?. Sadly, I don't have something that recreates it from scratch, but I do have the index if someone want to have a look at it (mail me directly and I will provide a download link).\r\n\r\nI will continue to investigate why this might happen, just wondering if someone stumbled on this exception before. Lucene 3.0.2 is used.","customfield_10010":null,"timetracking":{},"customfield_12310120":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10121","value":"New","id":"10121"}],"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"25344","summary":"ArrayIndexOutOfBoundsException when iterating over TermDocs","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kimchy","name":"kimchy","emailAddress":"kimchy at mac dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Shay Banon","active":true},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kimchy","name":"kimchy","emailAddress":"kimchy at mac dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Shay Banon","active":true},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":17,"total":17,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12914401","id":"12914401","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"This looks like index corruption -- somehow the deleted docs bit vector is too small for that segment.  We have to get to the root cause of how the corruption happened.\r\n\r\nEG if you can enable IndexWriter's infoStream, then get the corruption to happen, and post the resulting log...\r\n\r\nAlso, try enabling assertions... it may catch the corruption sooner.\r\n\r\nCan you describe how you use Lucene?  Do you do any direct file IO in the index dir?  (eg, for backup/restore or something).\r\n\r\nAre you certain only one writer is open on the index?  (Do you disable Lucene's locking?)\r\n\r\nWhich OS, filesystem, java impl are you using?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2010-09-24T10:23:22.855+0000","updated":"2010-09-24T10:23:22.855+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12981649","id":"12981649","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi, \r\n\r\nI am getting this issue as well?\r\nWe are doing quite a lot of update updates during indexing. Could this be causing the problem ?\r\n\r\nThis seems to only have happened when we deployed to our linux test server - it didn't appear to occur on MAC OS X during development - with the same data set.\r\n\r\nDoes this only affect Lucene 3.0.2 ? Would a rollback be a good work around ? \r\n\r\n\r\n\r\nThe exact stack strace:\r\n{code}\r\njava.lang.ArrayIndexOutOfBoundsException: 5475\r\n        at org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n        at org.apache.lucene.index.SegmentTermDocs.next(SegmentTermDocs.java:127)\r\n        at org.apache.lucene.index.SegmentTermPositions.next(SegmentTermPositions.java:102)\r\n        at org.apache.lucene.index.SegmentTermDocs.skipTo(SegmentTermDocs.java:207)\r\n        at org.apache.lucene.search.PhrasePositions.skipTo(PhrasePositions.java:52)\r\n        at org.apache.lucene.search.PhraseScorer.advance(PhraseScorer.java:120)\r\n        at org.apache.lucene.search.IndexSearcher.searchWithFilter(IndexSearcher.java:249)\r\n        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:218)\r\n        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:199)\r\n        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:177)\r\n        at org.apache.lucene.search.MultiSearcher$MultiSearcherCallableWithSort.call(MultiSearcher.java:410)\r\n        at org.apache.lucene.search.MultiSearcher.search(MultiSearcher.java:230)\r\n        at org.apache.lucene.search.Searcher.search(Searcher.java:49)\r\n\r\n{code}","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-14T07:15:05.397+0000","updated":"2011-01-14T07:17:33.467+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12981650","id":"12981650","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"I've also noticed this occurring since I started using a numeric field and accessing the its field cache for boosting.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-14T07:16:24.426+0000","updated":"2011-01-14T07:16:24.426+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12981843","id":"12981843","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Can you run CheckIndex on this index and post the result?  And, enable assertions.\r\n\r\nAnd if possible turn on IndexWriter's infoStream and capture/post the output leading up to the corruption.\r\n\r\nMany updates during indexing is just fine... and I know whether rolling back to older Lucene releases will help (until we've isolated the issue).  But: maybe try rolling forward to 3.0.3?  It's possible you're hitting a big fixed in 3.0.3 (though this doesn't ring a bell for me).","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-14T17:58:01.237+0000","updated":"2011-01-14T17:58:01.237+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12982468","id":"12982468","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi MIchael, \r\n\r\nThanks for the update. I have added an infoStream to the writer and triggered a re-index. Unfortunately, I didn't see the corruption occur this time.\r\nI am about to deploy to a different environment so will let you know.\r\n\r\nWe are already upgraded to Lucene 3.0.3, unfortunately.\r\n\r\nHopefully we will see the problem re-occur and be able to capture the necessary output to track down the problem.\r\n\r\nI've also added a call to writer.prepareCommit(). Previously, only writer.commit() was being called. Could that have an effect ?\r\n\r\nCheers,\r\nNick","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-17T04:01:21.126+0000","updated":"2011-01-17T04:01:21.126+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12982597","id":"12982597","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"OK thanks.  Hopefully we can catch this under infoStream's watch.\r\n\r\nNot calling prepareCommit is harmless -- IW simply calls it for you under the hood when commit() is called, if you hadn't already called prepareCommit().\r\n\r\nThe two APIs are separate in case you want to involve Lucene in a 2 phased commit w/ other resources.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-17T11:25:30.992+0000","updated":"2011-01-17T11:25:30.992+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12985474","id":"12985474","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi Michael, \r\n\r\nWe managed to catch this happening again. I've created a bug for our project over at: http://jira.atlassian.com/browse/CRUC-5486 ( Since I can't seem to upload the log to this JIRA instance?).\r\n\r\nMy hunch is that this occurs if a search is performed at the same time as a re-index - and a lucene cache is potentially not being closed/cleared correctly.\r\nIt appears that a re-start of the application causes this problem to go away.\r\n\r\nCheers,\r\nNick.\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-24T00:56:34.448+0000","updated":"2011-01-24T00:56:34.448+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12985833","id":"12985833","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Thanks Nick; I'll look at the log.\r\n\r\nAside: you should be able to attach files here... not sure why you saw otherwise...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-24T17:30:55.240+0000","updated":"2011-01-24T17:30:55.240+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12985873","id":"12985873","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Nick, the infoStream output looks healthy -- I don't see any exceptions.  Can you post the output from CheckIndex against the index that corresponds to this infoStream?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-24T18:25:11.075+0000","updated":"2011-01-24T18:25:11.075+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12986209","id":"12986209","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi Michael, \r\n\r\nThanks for looking at that log.\r\nI ran CheckIndex on the corrupt index - and have attached the output here. It doesn't appear to have detected any problems.\r\n\r\nDo you think this problem could be caused by a cache not being flushed correctly ?\r\n\r\nCheers,\r\nNick","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-25T04:14:13.047+0000","updated":"2011-01-25T04:14:13.047+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12986566","id":"12986566","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Hmmm --- given that exception, I would expect CheckIndex to have also seen this issue.\r\n\r\nSearching at the same time as indexing shouldn't cause this.  Lucene doesn't cache postings, but does cache metadata for the term, though I can't see how that could lead to this exception.\r\n\r\nThis could also be a hardware issue?  Do you see the problem on more than one machine?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-25T18:11:03.067+0000","updated":"2011-01-25T18:11:03.067+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12987328","id":"12987328","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi MIchael, \r\n\r\nWe have now seen this issue on more than 1 machine. I don't think it is a hardware issue.\r\nWe are using the ConcurrentMergeScheduler on the writer - so not sure if that has known issues?\r\nA restart definitely 'fixes' this problem though.\r\n\r\nThe stack-trace is:\r\n\r\n{code}\r\njava.lang.ArrayIndexOutOfBoundsException: 3740\r\n\tat org.apache.lucene.util.BitVector.get(BitVector.java:104)\r\n\tat org.apache.lucene.index.SegmentTermDocs.next(SegmentTermDocs.java:127)\r\n\tat org.apache.lucene.index.SegmentTermPositions.next(SegmentTermPositions.java:102)\r\n\tat org.apache.lucene.search.PhrasePositions.next(PhrasePositions.java:41)\r\n\tat org.apache.lucene.search.PhraseScorer.init(PhraseScorer.java:147)\r\n\tat org.apache.lucene.search.PhraseScorer.nextDoc(PhraseScorer.java:78)\r\n\tat org.apache.lucene.search.DisjunctionSumScorer.initScorerDocQueue(DisjunctionSumScorer.java:101)\r\n\tat org.apache.lucene.search.DisjunctionSumScorer.<init>(DisjunctionSumScorer.java:85)\r\n\tat org.apache.lucene.search.BooleanScorer2$1.<init>(BooleanScorer2.java:154)\r\n\tat org.apache.lucene.search.BooleanScorer2.countingDisjunctionSumScorer(BooleanScorer2.java:149)\r\n\tat org.apache.lucene.search.BooleanScorer2.makeCountingSumScorerNoReq(BooleanScorer2.java:218)\r\n\tat org.apache.lucene.search.BooleanScorer2.makeCountingSumScorer(BooleanScorer2.java:208)\r\n\tat org.apache.lucene.search.BooleanScorer2.<init>(BooleanScorer2.java:101)\r\n\tat org.apache.lucene.search.BooleanQuery$BooleanWeight.scorer(BooleanQuery.java:336)\r\n\tat org.apache.lucene.search.function.CustomScoreQuery$CustomWeight.scorer(CustomScoreQuery.java:359)\r\n\tat org.apache.lucene.search.BooleanQuery$BooleanWeight.scorer(BooleanQuery.java:306)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:210)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:170)\r\n\tat org.apache.lucene.search.MultiSearcher$MultiSearcherCallableNoSort.call(MultiSearcher.java:363)\r\n\tat org.apache.lucene.search.MultiSearcher.search(MultiSearcher.java:208)\r\n\tat org.apache.lucene.search.Searcher.search(Searcher.java:98)\r\n{code}\r\n\r\nI am going to spend some time trying to reproduce this locally today, with a debugger attached.\r\n\r\nCheers,\r\nNick","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-27T01:17:20.552+0000","updated":"2011-01-27T01:17:20.552+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12987415","id":"12987415","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi Michael, \r\n\r\nWe've done some analysis on how we are using Lucene and discovered the following:\r\n* the *only* time we construct a new reader {{IndexReader.open(directory, true)}} is when we search the index for the first time since the server start.\r\n* every other time, we are using reader.reopen() each time we detect that a write has occurred to the index.\r\n{code}\r\n                            final IndexReader newReader = oldReader.reopen();\r\n                            if (newReader != oldReader) {\r\n                                oldReader.decRef();\r\n                                reader = newReader;\r\n                            }\r\n{code}\r\n* the bug definitely goes away when the system is restarted and a new Reader is instantiated.\r\n* once we see the AIOOBE, it happens on _every search_ until we restart\r\n* running CheckIndex never reports any errors\r\n\r\nTherefore we believe that reader.reopen() is most likely causing certain data structures to be shared and creates inconsistency which leads to this exception.\r\n\r\nThe latest stack trace we are getting is in the comment above.\r\n\r\nGiven this information would you have any more clues for us?\r\n\r\nThank you very much for your help so far,\r\ngreatly appreciated.\r\nNick\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-27T07:19:35.639+0000","updated":"2011-01-27T07:19:35.639+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12987829","id":"12987829","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi Michael, \r\n\r\nWe have a memory dump of the instance that is affected by this. Would you know the best place to start looking for the possibly outdated BitVector?\r\nWe could make this available to you if you wish - all 1.8GB of it though :( \r\n\r\nCheers,\r\nNick\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-01-27T23:31:02.031+0000","updated":"2011-01-27T23:31:02.031+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12988086","id":"12988086","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Nick, are you running Lucene w/ asserts enabled?  Are you able to take a src patch and run it through your test?  If so, I can add some verbosity/asserts and we can try to narrow this down.\r\n\r\nIt does  sound like somehow the wrong delete BitVector is getting associated w/ a SegmentReader.\r\n\r\nIt looks like you don't use NRT readers right?  Ie, you always .commit() from IW and then do IR.reopen?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-01-28T14:01:31.692+0000","updated":"2011-01-28T14:01:31.692+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12991315","id":"12991315","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"body":"Hi Michael, \r\n\r\nThis issue was entirely a problem with our code, and I doubt Lucene could have done a better job.\r\n\r\nThe problem was that on upgrade of the index (done when fields have changed etc), we recreate the index in the same location using \r\n{{IndexWriter.create(directory, analyzer, true, MAX_FIELD_LENGTH)}}.\r\n\r\nSome code was added just before this however, that deleted every single file in the directory. This meant that some other thread performing a search could have seen a corrupt index, thus causing the AIOOBE. The developer was paranoid that IndexWriter.create was leaving old files lying around.\r\n\r\nI'm glad we got to the bottom of this, and very much so that it was not a bug in Lucene!\r\n\r\nThanks again for helping us track this down.\r\n\r\nBest Regards,\r\nNick Pellow\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=npellow","name":"npellow","emailAddress":"npellow at atlassian dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Nick Pellow","active":true},"created":"2011-02-07T09:48:00.400+0000","updated":"2011-02-07T09:48:00.400+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12475017/comment/12991545","id":"12991545","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"body":"Ahh, thanks for bringing closure Nick!  Although, I'm a little confused how removing files from the index while readers are using it, could lead to those exceptions...\r\n\r\nNote that it's perfectly fine to pass create=true to IW, over an existing index, even while readers are using it; IW will gracefully remove the old files itself, even if open IRs are still using them. IW just makes a new commit point that drops all references to prior segments...\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikemccand","name":"mikemccand","emailAddress":"lucene at mikemccandless dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael McCandless","active":true},"created":"2011-02-07T19:46:51.215+0000","updated":"2011-02-07T19:46:51.215+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/LUCENE-2666/votes","votes":1,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i04p6f:"}}