{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12652481","self":"https://issues.apache.org/jira/rest/api/latest/issue/12652481","key":"SOLR-4920","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310230","id":"12310230","key":"SOLR","name":"Solr","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310230&avatarId=22151","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310230&avatarId=22151","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310230&avatarId=22151","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310230&avatarId=22151"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10150","id":"10150","description":"Lucene-related projects","name":"Lucene"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12324324","id":"12324324","description":"Major release after 4.3","name":"4.4","archived":false,"released":true,"releaseDate":"2013-07-23"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12310220":"2013-06-13 06:47:47.493","customfield_12312323":null,"customfield_12310420":"332805","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_40307226_*|*_5_*:*_1_*:*_0","customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2013-06-13T07:15:24.448+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/SOLR-4920/watchers","watchCount":3,"isWatching":false},"created":"2013-06-12T20:03:37.245+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12312330":null,"customfield_12311120":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12324128","id":"12324128","description":"Major release after 4.2","name":"4.3","archived":false,"released":true,"releaseDate":"2013-05-05"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12321664","id":"12321664","description":"Current trunk","name":"Trunk","archived":false,"released":false}],"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shalinmangar","name":"shalinmangar","emailAddress":"shalin dot mangar at lucidworks dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=shalinmangar&avatarId=19501","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=shalinmangar&avatarId=19501","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=shalinmangar&avatarId=19501","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=shalinmangar&avatarId=19501"},"displayName":"Shalin Shekhar Mangar","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2014-10-29T14:00:19.179+0000","customfield_12312335":null,"customfield_12312336":null,"customfield_12311720":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12312438","id":"12312438","name":"contrib - DataImportHandler","description":"http://wiki.apache.org/solr/DataImportHandler"}],"timeoriginalestimate":null,"description":"JdbcDataSource will incorrectly suppress exceptions when retrieving a connection from a JNDI context and fall back to trying to use DriverManager to obtain a connection. This makes it impossible to troubleshoot misconfigured JNDI DataSource.\r\n\r\nAdditionally, when a SQLException is thrown while initializing a connection, such as in setAutoCommit(), the connection will not be closed. This can cause a resource leak.\r\n\r\nA patch will be attached with unit tests that addresses both issues.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"333134","summary":"DIH JdbcDataSource exception handling","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=chris.eldredge","name":"chris.eldredge","emailAddress":"chris dot eldredge at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Chris Eldredge","active":true},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=chris.eldredge","name":"chris.eldredge","emailAddress":"chris dot eldredge at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Chris Eldredge","active":true},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":6,"total":6,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/13681576","id":"13681576","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=chris.eldredge","name":"chris.eldredge","emailAddress":"chris dot eldredge at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Chris Eldredge","active":true},"body":"Patch against r1492257.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=chris.eldredge","name":"chris.eldredge","emailAddress":"chris dot eldredge at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Chris Eldredge","active":true},"created":"2013-06-12T20:07:37.531+0000","updated":"2013-06-12T20:07:37.531+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/13681960","id":"13681960","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=commit-tag-bot","name":"commit-tag-bot","emailAddress":"root-jira-commit_tag_bot at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=commit-tag-bot&avatarId=16176","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=commit-tag-bot&avatarId=16176","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=commit-tag-bot&avatarId=16176","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=commit-tag-bot&avatarId=16176"},"displayName":"Commit Tag Bot","active":true},"body":"[trunk commit] shalin\r\nhttp://svn.apache.org/viewvc?view=revision&revision=1492537\r\n\r\nSOLR-4920: JdbcDataSource incorrectly suppresses exceptions when retrieving a connection from  a JNDI context and falls back to trying to use DriverManager to obtain a connection. Additionally,  if a SQLException is thrown while initializing a connection, such as in setAutoCommit(), the  connection will not be closed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=commit-tag-bot","name":"commit-tag-bot","emailAddress":"root-jira-commit_tag_bot at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=commit-tag-bot&avatarId=16176","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=commit-tag-bot&avatarId=16176","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=commit-tag-bot&avatarId=16176","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=commit-tag-bot&avatarId=16176"},"displayName":"Commit Tag Bot","active":true},"created":"2013-06-13T06:47:47.493+0000","updated":"2013-06-13T06:47:47.493+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/13681963","id":"13681963","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=commit-tag-bot","name":"commit-tag-bot","emailAddress":"root-jira-commit_tag_bot at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=commit-tag-bot&avatarId=16176","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=commit-tag-bot&avatarId=16176","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=commit-tag-bot&avatarId=16176","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=commit-tag-bot&avatarId=16176"},"displayName":"Commit Tag Bot","active":true},"body":"[branch_4x commit] shalin\r\nhttp://svn.apache.org/viewvc?view=revision&revision=1492538\r\n\r\nSOLR-4920: JdbcDataSource incorrectly suppresses exceptions when retrieving a connection from  a JNDI context and falls back to trying to use DriverManager to obtain a connection. Additionally,  if a SQLException is thrown while initializing a connection, such as in setAutoCommit(), the  connection will not be closed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=commit-tag-bot","name":"commit-tag-bot","emailAddress":"root-jira-commit_tag_bot at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=commit-tag-bot&avatarId=16176","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=commit-tag-bot&avatarId=16176","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=commit-tag-bot&avatarId=16176","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=commit-tag-bot&avatarId=16176"},"displayName":"Commit Tag Bot","active":true},"created":"2013-06-13T06:50:22.717+0000","updated":"2013-06-13T06:50:22.717+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/13681982","id":"13681982","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shalinmangar","name":"shalinmangar","emailAddress":"shalin dot mangar at lucidworks dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=shalinmangar&avatarId=19501","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=shalinmangar&avatarId=19501","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=shalinmangar&avatarId=19501","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=shalinmangar&avatarId=19501"},"displayName":"Shalin Shekhar Mangar","active":true},"body":"Fixed.\r\n\r\nThanks Chris!","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shalinmangar","name":"shalinmangar","emailAddress":"shalin dot mangar at lucidworks dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=shalinmangar&avatarId=19501","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=shalinmangar&avatarId=19501","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=shalinmangar&avatarId=19501","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=shalinmangar&avatarId=19501"},"displayName":"Shalin Shekhar Mangar","active":true},"created":"2013-06-13T07:15:24.465+0000","updated":"2013-06-13T07:15:24.465+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/13716791","id":"13716791","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_rowe","name":"steve_rowe","emailAddress":"sarowe at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Rowe","active":true},"body":"Bulk close resolved 4.4 issues","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_rowe","name":"steve_rowe","emailAddress":"sarowe at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Rowe","active":true},"created":"2013-07-23T18:38:36.287+0000","updated":"2013-07-23T18:38:36.287+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12652481/comment/14188359","id":"14188359","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mkhludnev","name":"mkhludnev","emailAddress":"gedel at yandex dot ru","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mikhail Khludnev","active":true},"body":"I face usability issue with  \r\n\r\n{code:title=JdbcDataSource.java}\r\n141 \ttry {\r\n142 \tc = DriverManager.getConnection(url, initProps);\r\n143 \t} catch (SQLException e) {\r\n144 \t// DriverManager does not allow you to use a driver which is not loaded through\r\n145 \t// the class loader of the class which is trying to make the connection.\r\n146 \t// This is a workaround for cases where the user puts the driver jar in the\r\n147 \t// solr.home/lib or solr.home/core/lib directories.\r\n148 \tDriver d = (Driver) DocBuilder.loadClass(driver, context.getSolrCore()).newInstance();\r\n149 \tc = d.connect(url, initProps);\r\n150 \t}\r\n{code}\r\n\r\nif I supply weird url, I've got SQLException, it's caught, then it calls c = d.connect(url, initProps); which returns null (which is pretty valid giving the javadoc). Then I have NPE where the connection is hit. There is no anything about SQLException reasons in the log. Isn't it worth to raise an issue? \r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mkhludnev","name":"mkhludnev","emailAddress":"gedel at yandex dot ru","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mikhail Khludnev","active":true},"created":"2014-10-29T14:00:19.179+0000","updated":"2014-10-29T14:00:19.179+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/SOLR-4920/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i1leu7:"}}