{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12347114","self":"https://issues.apache.org/jira/rest/api/latest/issue/12347114","key":"DERBY-1629","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312590","id":"12312590","description":"","name":"10.3.1.4","archived":false,"released":true,"releaseDate":"2007-08-10"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/3","id":"3","description":"The problem is a duplicate of an existing issue.","name":"Duplicate"},"customfield_12310220":"2006-08-02 03:06:40.0","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"22608","customfield_12310222":"1_*:*_1_*:*_25562160857_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2007-05-24T20:49:40.857+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1629/watchers","watchCount":0,"isWatching":false},"created":"2006-08-02T00:13:40.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12313413","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12313413","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12348251","key":"DERBY-1729","self":"https://issues.apache.org/jira/rest/api/2/issue/12348251","fields":{"summary":"Invoking Java stored procedure that contains GRANT or REVOKE statement with CONTAINS SQL should fail.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12315726","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12315726","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12367127","key":"DERBY-2545","self":"https://issues.apache.org/jira/rest/api/2/issue/12367127","fields":{"summary":"testModifiesSql(org.apache.derbyTesting.functionTests.tests.lang.ProcedureInTriggerTest)junit.framework.ComparisonFailure: Unexpected SQL state. expected:<3800[0]> but was:<3800[1]>","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2011-01-21T17:49:09.751+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11407","id":"11407","name":"JDBC"},{"self":"https://issues.apache.org/jira/rest/api/2/component/11408","id":"11408","name":"SQL"}],"timeoriginalestimate":null,"description":"In Java SE 6 runtime environments, an application may not get the SQL Exception with SQL State 38000 when execution of a trigger or procedure fails with an exception caused by Derby internals.  Instead, they will get the underlying exception with it's SQL State.  For an example of this, see lang/procedureInTrigger.sql, which has different output for Java SE 6 (encoded in the master/jdk16/procedureInTrigger.out file) than for other Java SE runtimes.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10420","value":"Regression","id":"10420"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"37555","summary":"Exceptions thrown by code in procedures or triggers are not handled/thrown correctly by Derby","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"subtasks":[],"customfield_12310090":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10101","value":"Release Note Needed","id":"10101"}],"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10052","value":"Normal","id":"10052"},"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":16,"total":16,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425103","id":"12425103","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"body":"fix typo","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"created":"2006-08-02T03:06:40.000+0000","updated":"2006-08-02T03:06:40.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425281","id":"12425281","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Here are various ways to tackle this problem:\r\n\r\n1) We could create a parallel universe of SQLException subclasses, which extend the JDBC4 SQLException subclasses and implement some vacuous, Derby-specific interface. These would be the exceptions raised by SQLExceptionFactory40. EmbedSQLException could implement this vacuous interface too. In the code above (StandardException.unexpectedUserException()), we could then check whether the exception class was an instance of the vacuous interface.\r\n\r\n+ I think this covers the cases\r\n- Bloats up the server with around 20 new classes\r\n- As more SQLException subclasses are added to JDBC, we will have to add additional parallel Derby classes\r\n\r\n2) We could check whether the errorCode was one of the Derby-specific severities. This would be our flag that the exception was generated by Derby.\r\n\r\n+ Not a lot of code bloat.\r\n- Has wormholes: What if the user-created exception uses one of our severities as its error code?\r\n\r\n3) We could check whether the passed-in SQLException's getCause() method returns an EmbedSQLException. This would be true for all exceptions created by SQLExceptionFactory40\r\n\r\n+ Also not a lot of code bloat\r\n- Still has the wormhole that the user-created exception could set a Derby exception as its cause\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2006-08-02T16:27:09.000+0000","updated":"2006-08-02T16:27:09.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425296","id":"12425296","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"body":"Thanks for your thoughts, Rick.  It seems to me that for (3) if a user set a Derby exception as a cause, getCause() would return a SQLException, not an EmbeddedSQLException, so I would argue your wormhole can be closed...\r\n\r\nBut I don't like how it relies on behavior that could be changed at any time, and it's overloading the intention of setCause()/getCause().  But unless we go for (1) I can't see any way out of piggybacking extra semantics on one of the SQLException methods..., and getCause() seems like the best choice.  \r\n\r\nI would suggest that whoever fixes this adds a comment to the SQLExceptionFactory40 code that indicates that changing the cause will impact other code and describe how and why.\r\n\r\nDavid","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"created":"2006-08-02T17:02:10.000+0000","updated":"2006-08-02T17:02:10.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425349","id":"12425349","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"Can the summary of this bug be changed to reflect the impact on/change to/incorect behavaiour an application would see. This will be a regression when running on jdk 16 for an application, but what exactly is the regression?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2006-08-02T19:20:07.000+0000","updated":"2006-08-02T19:20:07.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425354","id":"12425354","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"I think it's also worth re-validating the requirements, some of the assumptions about that method are from the old Cloudscape days when any java method could be executed from SQL. Looking again it seems as though the current behaviour for routines is wrong and would not require knowing if an exception was thrown by Derby or not. Other uses of the method might though. The behaviour for routines is defined in SQL part 13, section 15.1, which seems to boil down to:\r\n\r\nIf a method throws an exception E  then\r\n\r\nif (method instance of java.sql.Exception)\r\n{\r\n   if SQL state starts with \"38\", is at least 5 characters and is not 38000\r\n       throw an exception with E's SQL state\r\n    else\r\n       throw an exception with SQL state 39001\r\n}\r\nelse\r\n{\r\n   throw an exception with SQL state 38000\r\n}\r\n\r\nAssuming we can take the meaning of \"class of  E is java.sql.SQLException\" to mean instanceof and not class has to be java.sql.SQLException,\r\nsince this was written before SQLException had sub-classes.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2006-08-02T19:37:55.000+0000","updated":"2006-08-02T19:37:55.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425355","id":"12425355","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"body":"Fixed this to describe user-perceived behavior.  Here is the original comment, which provides useful implementation details:\r\n\r\nIn non-JDK 1.6 builds, the exceptions Derby throws are all of class EmbedSQLException. As of JDK 1.6, that is no longer true. Instead we throw a \"native\" SQL Exception.\r\n\r\nThat makes the following code incorrect:\r\n\r\npublic static StandardException unexpectedUserException(Throwable t)\r\n{\r\n/*\r\n** If we have a SQLException that isn't a Util\r\n** (i.e. it didn't come from cloudscape), then we check\r\n** to see if it is a valid user defined exception range\r\n** (38001-38XXX). If so, then we convert it into a\r\n** StandardException without further ado.\r\n*/\r\nif ((t instanceof SQLException) &&\r\n!(t instanceof EmbedSQLException))\r\n{\r\nSQLException sqlex = (SQLException)t;\r\nString state = sqlex.getSQLState();\r\nif ((state != null) &&\r\n(state.length() == 5) &&\r\nstate.startsWith(\"38\") &&\r\n!state.equals(\"38000\"))\r\n{\r\nStandardException se = new StandardException(state, sqlex.getMessage());\r\nif (sqlex.getNextException() != null)\r\n{\r\nse.setNestedException(sqlex.getNextException());\r\n}\r\nreturn se;\r\n}\r\n}\r\n\r\nI am not sure how we can detect internally-thrown SQL Exceptions and distinguish them from user exceptions, but this does need to be looked at.\r\n\r\nRight now procedureInTrigger.sql is failing for JDK 1.6 due to this error. I may check in a jdk16-specific version of this file so at least derbyall can pass. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"created":"2006-08-02T19:41:50.000+0000","updated":"2006-08-02T19:41:50.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425356","id":"12425356","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"body":"I think what you described is in the SQL spec is not what is happening in this code right now, and should be fixed.  And I think you're right that this does not require us to know whether the exception is a Derby exception or not, who knows, the procedure could be calling some other backend database.  That simplifies things I think.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"created":"2006-08-02T19:46:41.000+0000","updated":"2006-08-02T19:46:41.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425365","id":"12425365","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"body":"Added a comment to the procedureInTrigger.sql script and fixed the main master file.  Also added a master file specific to jdk16.  \r\nI noticed procedureInTrigger.out also exists in a j9-specific directory, but as I don' t have the j9 VM to verify I didn't try to fix this file.\r\n\r\nCommitted revision 42818","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"created":"2006-08-02T20:15:20.000+0000","updated":"2006-08-02T20:15:20.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425634","id":"12425634","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"attaching a patch - DERBY-1629_j9canon.diff that updates the j9_22 canon. tested the test with wctme5.7.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2006-08-03T23:25:04.000+0000","updated":"2006-08-03T23:25:04.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12425860","id":"12425860","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"body":"Committed Myrna's patch, revision 428887","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davidvc","name":"davidvc","emailAddress":"david at vancouvering dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"David Van Couvering","active":true},"created":"2006-08-04T21:16:37.000+0000","updated":"2006-08-04T21:16:37.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12435866","id":"12435866","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Moving to 10.2.2.0.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2006-09-19T15:18:07.000+0000","updated":"2006-09-19T15:18:07.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12440571","id":"12440571","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"I think there may be a correction to the SQL spec for the correct way to handle exceptions. I don't have the details, just saw it while I was searching for something else. The correction is in an official SQL standard correction document which modifies the text in SQL Part 13 which itself modifies the SQL/Foundation spec. Thus it's sometimes confusing to realise what exactly is expected :-)","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2006-10-06T18:04:36.000+0000","updated":"2006-10-06T18:04:36.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12456042","id":"12456042","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Move to 10.2.3.0.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2006-12-06T14:34:27.000+0000","updated":"2006-12-06T14:34:27.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12467583","id":"12467583","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"body":"Unsetting Fix Version for unassigned issues.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"created":"2007-01-25T20:36:49.936+0000","updated":"2007-01-25T20:36:49.936+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12488725","id":"12488725","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"When this gets fixed, the if (!JDBC.vmsupportsJDBC4) check in test lang/ProcedureInTriggerTest should be removed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2007-04-13T17:39:47.554+0000","updated":"2007-04-13T17:39:47.554+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12347114/comment/12498827","id":"12498827","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"It seems like this issue is a duplicate of DERBY-1440.  At least, Knut Anders patch removes the check in lang/ProcedureInTriggerTest here mention by Myrna, and which seems to fit the original description of the problem.  I am not quite sure I understand all the comments made on this JIRA, and whether there are other issues here, but since the original problem seems to be solved, I suggest this JIRA should be closed. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2007-05-24T20:49:40.823+0000","updated":"2007-05-24T20:49:40.823+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1629/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06siv:"}}